version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.48
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Debugging"
          command: pwd && ls -al ~/project && ls -al ~/project/site
      - run:
          name: "Run Hugo"
          command: hugo -v -s ~/project/site -d ~/project/public
      - run:
          name: "Test site"
          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: |
          sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          sudo gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gsutil rsync -R ~/project/public/ gs://www.workablenetwork.com
