version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.48
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Debugging"
          command: pwd && ls -al ~/project && ls -al ~/project/site
      - run:
          name: "Run Hugo"
          command: hugo -v -s ~/project/site -d ~/project/public
      - run:
          name: "Test site"
          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
