version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.48
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s src/ --config=./site/build.yml -d ../public
      - run:
          name: "Startup school marketing site"
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
